### PR TITLE
feat: rewrite and drop then-fs

### PR DESCRIPTION
**Pull request by FauxFaux**
`then-fs` triggers a bug in `jest`, making it leak memory like a pro. We can replace `then-fs` with `util.promisify`, because we support only new enough node, and make nearly no use of the filesystem (or anything) anyway.

I ended up rewriting the library to `await`-style at the same time, because the tests were failing for no reason, and it was easier to rewrite it than work out why there was no stack trace (so angry).

Reviewer warning: This library uses `postinstall` in the worst way possible: you cannot safely run any `npm` command except `install` *in a clean directory*.

### Notes for reviewer

I only care about the last commit, if we want to merge just that. Each commit individually seems fine, though.

### CODE REVIEW

**Comment by FauxFaux** [comment]
I believe this changes the way negative caching works, because of the promise chain unwinding. Let's merge the simple parts as #16 then try again.

**Comment by aviadhahami** [comment]
@FauxFaux - is this still needed?

**Comment by FauxFaux** [comment]
The bug, from registry's perspective, was fixed in https://github.com/snyk/try-require/commit/98cce8839146c7a33b5c0ec44498b2c1a5d64c0f#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

If you want all of the rest of the work, wherein the whole codebase is modernised and tested, then you're welcome to pick that up?

**Comment by anthogez** [comment]
@FauxFaux I'm closing this one, if still relevant feel free to reopen

**Comment by FauxFaux** [comment]
It's mostly adding tests. If you don't want the tests, sure, whatever.

**Pull request closed without merging**
